FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        python2.7 \
        python-numpy \
        gawk \
        coreutils \
        grep \
        sed \
        ca-certificates \
    && ln -sf /usr/bin/python2.7 /usr/local/bin/python2 \
    && ln -sf /usr/bin/python2.7 /usr/local/bin/python \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work
